---
- name: Clone checkbox.io Github repository
  become: yes
  git: >
    repo=https://github.com/chrisparnin/checkbox.io.git
    dest=checkbox.io
    update=no
    force=yes

- name: clone iTrust repository
  become: yes
  git: >
      repo=git@github.ncsu.edu:engr-csc326-staff/iTrust2-v2.git
      key_file=.ssh/id_rsa
      dest=iTrust2-v2
      accept_hostkey=yes
      update=no
      force=yes
